--- 
language: ruby
rvm:
- 2.0.0
- 2.1.8
- 2.2.4
- 2.3.0
- rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
  exclude:
    - rvm: 2.0.0
      env: TASK=coffeelint
    - rvm: 2.0.0
      env: TASK=rails_best_practices
    - rvm: 2.0.0
      env: TASK=rubocop
    - rvm: 2.0.0
      env: TASK=spec DB=mysql
    - rvm: 2.0.0
      env: TASK=spec DB=postgresql
    - rvm: 2.0.0
      env: TASK=spec:javascript

    - rvm: 2.1.8
      env: TASK=coffeelint
    - rvm: 2.1.8
      env: TASK=rails_best_practices
    - rvm: 2.1.8
      env: TASK=rubocop
    - rvm: 2.1.8
      env: TASK=spec DB=mysql
    - rvm: 2.1.8
      env: TASK=spec DB=postgresql
    - rvm: 2.1.8
      env: TASK=spec:javascript

    - rvm: 2.2.4
      env: TASK=coffeelint
    - rvm: 2.2.4
      env: TASK=rails_best_practices
    - rvm: 2.2.4
      env: TASK=rubocop
    - rvm: 2.2.4
      env: TASK=spec DB=mysql
    - rvm: 2.2.4
      env: TASK=spec DB=postgresql
    - rvm: 2.2.4
      env: TASK=spec:javascript

    - rvm: rbx-2
      env: TASK=coffeelint
    - rvm: rbx-2
      env: TASK=rails_best_practices
    - rvm: rbx-2
      env: TASK=rubocop
    - rvm: rbx-2
      env: TASK=spec DB=mysql
    - rvm: rbx-2
      env: TASK=spec DB=postgresql
    - rvm: rbx-2
      env: TASK=spec:javascript
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TASK=coffeelint
    - TASK=rails_best_practices
    - TASK=rubocop
    - TASK=spec
    - TASK=spec DB=mysql
    - TASK=spec DB=postgresql
    - TASK=spec:javascript
before_install:
- sh -e /etc/init.d/xvfb start
- if [ "$DB" == 'mysql' ]; then echo "gem 'mysql2', '~> 0.3.13'" >> Gemfile; fi
before_script:
- if [ -n "$DB" ]; then cp config/database.yml.$DB config/database.yml; fi
- bundle exec rake db:create db:migrate
sudo: false
addons:
  postgresql: "9.4"
  apt:
    packages:
      - libgmp-dev
script: bundle exec rake $TASK
