--- 
language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.6
- 2.2.2
- rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx-19mode
env:
  global:
    secure: 'TRcTBwwBWOQayJnGYRQFOGUBN9ZoBqw8WGFf+1vf46kJewXvdA5QAEtwOmdDnlpfTCw2bwZsJLOz3EcvtCYtLmQLPlUEs6jjgwmmnhgcp1IRFvEmW77mjd/gZuwPkrjVJSkPtfMVPv91+dKxofoBSTKSHuf1ZAnacselVVQQ+MM='
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:migrate
sudo: false
after_success:
- '[ "$DOCKER_HUB_TOKEN" ] && curl -H "Content-Type: application/json" --data ''{"build": true}'' -X POST https://registry.hub.docker.com/u/mm62/meme-captain-web/trigger/$DOCKER_HUB_TOKEN/'
