--- 
language: ruby
rvm: 
- 1.9.2
- 1.9.3
before_install: 
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script: 
- bundle exec rake db:migrate
env: 
  global: 
  - secure: |-
      bwGbgLE1l+jUjrPqbfYvGhXO0uvKFevTsS04dS63RHTeCrhoRTWdRitZm/sg
      gOJkDE15hhnCTx7TDFdjz3k8gz3ZA1uqJ29yrgasTXGnrdiawTZoXx1kWFW5
      xzPAj5Y/LEar0bOWIeRjLp8BqtG0uwnv9eBBasid2GlWbmIWKsw=
  - HEROKU_APP=mcalpha
after_succes:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sudo sh
  - git remote add heroku git@heroku.com:${HEROKU_APP}.git
  - heroku keys:add
  - LAST_KEY=`heroku keys | tail -2 | cut -f 3 -d ' '`
  - git push heroku master
  - heroku keys:remove $LAST_KEY
