--- 
language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.6
- 2.2.2
- rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx-19mode
env:
  global:
    - DISPLAY=:99.0
before_install:
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:migrate
sudo: false
