--- 
language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.6
- 2.2.3
- rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
  exclude:
    - rvm: 1.9.3
      env: DB=database.yml.postgresql
    - rvm: 2.0.0
      env: DB=database.yml.postgresql
    - rvm: 2.1.6
      env: DB=database.yml.postgresql
    - rvm: rbx-2
      env: DB=database.yml.postgresql
    - rvm: 1.9.3
      env: DB=database.yml.mysql
    - rvm: 2.0.0
      env: DB=database.yml.mysql
    - rvm: 2.1.6
      env: DB=database.yml.mysql
    - rvm: rbx-2
      env: DB=database.yml.mysql
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - DB=database.yml.mysql
    - DB=database.yml.postgresql
    - DB=database.yml.sqlite
before_install:
- sh -e /etc/init.d/xvfb start
- ./ci/add_mysql_gem.sh
before_script:
- cp config/$DB config/database.yml
- bundle exec rake db:create db:migrate
sudo: false
addons:
  postgresql: "9.4"
